SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `tour_image`;
TRUNCATE TABLE `review`;
TRUNCATE TABLE `purchase`;
TRUNCATE TABLE `tour`;
TRUNCATE TABLE `user_role`;
TRUNCATE TABLE `role`;
TRUNCATE TABLE `user`;
SET FOREIGN_KEY_CHECKS = 1;
