package com.sfedu.touragency.imageprovider;

import java.io.*;

/**
 * Service for saving images to disk
 */
public interface ImageService {
    /**
     * Writes the given input stream to a file with the given extension
     * @param is a binary image input stream
     * @param ext image extension
     * @return the name of the image file
     */
    String save(InputStream is, String ext);

    /**
     * Writes the image by the given name to the output stream
     * @param filename is a file name generated by save(is, ext)
     * @param os
     * @return true if the operation was successful, false otherwise
     */
    boolean load(String filename, OutputStream os);

    /**
     * Delete previously saved image by filename
     * @return true if the operation was successful, false otherwise
     */
    boolean delete(String filename);

    /**
     * Return the thumbnail name
     * @param filename
     * @return
     */
    String thumbnailName(String filename);
}
