DROP TABLE IF EXISTS test;

CREATE TABLE IF NOT EXISTS test (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  col VARCHAR(25) NOT NULL DEFAULT NULL,
  PRIMARY KEY(id)
);

INSERT INTO test (col) VALUES ('x');
INSERT INTO test (col) VALUES ('y');
INSERT INTO test (col) VALUES ('z');
